Warning in <TInterpreter::ReadRootmapFile>: class  edm::ValueMap<float> found in libDataFormatsCommon.so  is already in libHiggsAnalysisHiggsToZZ4Leptons.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::Wrapper<edm::ValueMap<float> > found in libDataFormatsCommon.so  is already in libHiggsAnalysisHiggsToZZ4Leptons.so 
Error in <TUnixSystem::FindDynamicLibrary>: libAnalysisPredictedDistribution[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /uscms_data/d3/zwang4/WORKSPCACE/ntuple/CMSSW_8_0_24/biglib/slc6_amd64_gcc530:/uscms_data/d3/zwang4/WORKSPCACE/ntuple/CMSSW_8_0_24/lib/slc6_amd64_gcc530:/uscms_data/d3/zwang4/WORKSPCACE/ntuple/CMSSW_8_0_24/external/slc6_amd64_gcc530/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/biglib/slc6_amd64_gcc530:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/lib/slc6_amd64_gcc530:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/external/slc6_amd64_gcc530/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/llvm/3.8.0-giojec2/lib64:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/gcc/5.3.0/lib64:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/gcc/5.3.0/lib:.:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/lcg/root/6.06.00-ikhhed5/lib:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64
Processing file root://cms-xrd-global.cern.ch//store/mc/RunIISummer16MiniAODv2/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/70000/045AF4D5-8CC1-E611-9F87-008CFA197D18.root
Traceback (most recent call last):
  File "LHEweightPrinter_fwlite.py", line 86, in <module>
    lheRun = h_lheRun.product() 
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/python/DataFormats/FWLite/__init__.py", line 86, in product
    raise self._exception
RuntimeError: getByLabel (LHERunInfoProduct, 'externalLHEProducer', '', '') failed

 *** Break *** segmentation violation
